import { FixSummary } from './types';
import { execCommand, logInfo } from './utils';

export function buildPrBody(summary: FixSummary): string {
  const status = summary.fullyResolved
    ? 'All TypeScript errors have been resolved.'
    : `${summary.errorsAfter} error(s) could not be automatically fixed and require manual attention.`;

  const filesSection = summary.filesFixed
    .map((f) => `- \`${f}\``)
    .join('\n');

  return `## TypeScript Auto-Fix

This PR was automatically generated by [better-tsc-fixer](https://github.com/Sachchaa/better-tsc-fixer).

### Summary

- **Errors before:** ${summary.errorsBefore}
- **Errors after:** ${summary.errorsAfter}
- **Files modified:** ${summary.filesFixed.length}

${status}

### Files Fixed

${filesSection}

---

> Please review the changes carefully before merging. The fixes were generated by an AI model and should be verified for correctness.`;
}

export async function createPullRequest(
  baseBranch: string,
  headBranch: string,
  title: string,
  body: string,
  githubToken: string,
): Promise<string> {
  logInfo(`Creating PR: ${headBranch} -> ${baseBranch}`);

  const { exitCode, stdout, stderr } = await execCommand(
    'gh',
    [
      'pr',
      'create',
      '--base',
      baseBranch,
      '--head',
      headBranch,
      '--title',
      title,
      '--body',
      body,
    ],
    {
      silent: false,
      env: {
        ...process.env,
        GH_TOKEN: githubToken,
      },
    },
  );

  if (exitCode !== 0) {
    throw new Error(`Failed to create PR: ${stderr}`);
  }

  const prUrl = stdout.trim();
  logInfo(`PR created: ${prUrl}`);
  return prUrl;
}
